{
 "title": "Monitoring Fuse Services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Estado",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Camel Redeliveries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_Redeliveries{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Camel Delta ProcessingTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_Redeliveries{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Tiempo máximo de procesamiento",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_MaxProcessingTime{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Camel Threads Bloqueados",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_ThreadsBlocked"
    }
   ]
  },
  {
   "title": "Mensajes completos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesCompleted{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Mensajes fallidos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesFailed{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Mensajes In flight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesInflight{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Mensajes Totales",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesTotal{type=\"routes\"}"
    }
   ]
  },
  {
   "title": "Camel Threads Interrumpidos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "org_apache_camel_ThreadsInterrupted"
    }
   ]
  },
  {
   "title": "Evolución Mensajes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesCompleted{type=\"routes\"}",
     "legendFormat": "Completos | {{route}}"
    },
    {
     "expr": "org_apache_camel_ExchangesFailed{type=\"routes\"}",
     "legendFormat": "Fallidos | {{route}}"
    },
    {
     "expr": "org_apache_camel_ExchangesTotal{type=\"routes\"}",
     "legendFormat": "Totales | {{route}}"
    }
   ]
  },
  {
   "title": "Threads JVM",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "Current" },
    { "expr": "jvm_threads_daemon", "legendFormat": "Daemon" },
    { "expr": "jvm_threads_deadlocked", "legendFormat": "Deadlock" }
   ]
  },
  {
   "title": "Estado evolucion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memoria JVM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "Contexto",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "org_apache_camel_ExchangesTotal",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}