apiVersion: v1
data:
  grafana.ini: |+

    [paths]
    data = /var/lib/grafana
    logs = /var/lib/grafana/logs
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [log]
    # Either "console", "file", "syslog". Default is console and  file
    # Use space to separate multiple modes, e.g. "console file"
    mode = console

    [security]
    # default admin user, created on startup
    admin_user = admin
    admin_password = redhat01

kind: ConfigMap
metadata:
  name: grafana-config